# Generated by Django 4.1.7 on 2023-03-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('position',), 'verbose_name_plural': 'Страви'},
        ),
    ]
