# Generated by Django 4.1.7 on 2023-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_menuitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва послуги')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name_plural': 'Послуги',
                'ordering': ('position',),
            },
        ),
    ]
