# Generated by Django 4.1.7 on 2023-03-06 15:14

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_servise_desc_remove_servise_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Повне ім'я")),
                ('profession', models.TextField(max_length=50, verbose_name='Посада')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Посада')),
                ('twi_url', models.URLField(blank=True, default='https://twitter.com/', verbose_name='Посилання на twitter')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Наша команда',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Повне ім'я")),
                ('profession', models.TextField(max_length=50, verbose_name='Посада')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
                'ordering': ('position',),
            },
        ),
    ]
