# Generated by Django 4.1.7 on 2023-03-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_team_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='desc',
        ),
    ]
