# Generated by Django 4.1.7 on 2023-03-06 16:09

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_team_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_1', models.TextField(max_length=500, verbose_name='Опис 1')),
                ('desc_2', models.TextField(max_length=500, verbose_name='Опис 2')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
                ('experience', models.SmallIntegerField(verbose_name='Роки роботи')),
                ('cook', models.SmallIntegerField(verbose_name='Кількість поварів')),
                ('img_1', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення 1')),
                ('img_2', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення 2')),
                ('img_3', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення 3')),
                ('img_4', models.ImageField(upload_to=main_page.utils.get_file_name, verbose_name='Зображення 4')),
            ],
            options={
                'verbose_name_plural': 'Про нас',
                'ordering': ('desc_1',),
            },
        ),
        migrations.AlterField(
            model_name='servise',
            name='title_2',
            field=models.CharField(default='text', max_length=50, verbose_name='Назва послуги 2'),
        ),
        migrations.AlterField(
            model_name='servise',
            name='title_3',
            field=models.CharField(default='text', max_length=50, verbose_name='Назва послуги 3'),
        ),
    ]
