# Generated by Django 4.1.7 on 2023-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_about_alter_servise_title_2_alter_servise_title_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email_booking', models.CharField(max_length=50, verbose_name='Пошта Booking')),
                ('email_general', models.CharField(max_length=50, verbose_name='Пошта General')),
                ('email_technical', models.CharField(max_length=50, verbose_name='Пошта Technical')),
                ('day_open', models.CharField(max_length=50, verbose_name='Робочі дні')),
                ('hours_of_work', models.CharField(max_length=50, verbose_name='Робочі години')),
                ('weekend_work', models.CharField(max_length=50, verbose_name='Робота в вихідні')),
                ('weekend_hours_of_work', models.CharField(max_length=50, verbose_name='Робочі години в вихідні')),
                ('twi_url', models.URLField(blank=True, default='https://twitter.com/', verbose_name='Посилання на twitter')),
                ('fb_url', models.URLField(blank=True, default='https://www.facebook.com/', verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/', verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram')),
            ],
            options={
                'verbose_name_plural': 'Контакти',
                'ordering': ('address',),
            },
        ),
    ]
